### ISSUE TITLE
Cannot get access to data files

### ISSUE THREAD

**Issue by gefeiwang** [chapkinlab/Single-cell-RNA-sequencing-reveals-how-the-aryl-hydrocarbon-receptor-shapes-cellular-differentiation#1]
Hi authors,

I am trying to download the data from the link [http://gofile.me/3zFkx/rQ6jClg0w](http://gofile.me/3zFkx/rQ6jClg0w), but it seems to be invalid now. How can I find the processed dataset with cell type annotation? Thank you.

**Comment by destinymullens** [comment]
Now that the paper has been published, the processed expression matrices have been deposited in the NCBI’s Gene Expression Omnibus (GEO) database under the accession number: [GSE167595](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE167595). Thank you for bringing it to our attention that the old, link from before publication was still on the GitHub page!

**Comment by gefeiwang** [comment]
Thank you for your reply!
